server:
  port: 40000

spring:
  application:
    name: openapi-cache
  redis:
    host: baseservice.qfjava.cn
    port: 8400
    password: redis001

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:30000/eureka